#!/bin/bash
# Regenerates each subject folder's ROUTINES.md from routines.tsv, and makes the
# runs/ and outputs/ folders each cadence needs. Safe to rerun; overwrites only ROUTINES.md.
set -euo pipefail
cd "$(dirname "$0")"
for d in [0-9]*/ ; do
  d=${d%/}
  subject=$(awk -F'|' -v f="$d" '$1==f && $2=="daily"{print $3}' routines.tsv | sed 's/^Signals: //; s/, Daily$//')
  {
    echo "# $subject Market Signals"
    echo
    echo "Three cloud routines. Generated by \`make-records.sh\` from \`routines.tsv\`. Do not hand-edit."
    echo
    echo "| Cadence | Routine name | Cron (universal time) | Model | Page title | Trigger id |"
    echo "|---|---|---|---|---|---|"
    awk -F'|' -v f="$d" '$1==f{
      c=$2; sub(/^wednesday$/,"Wednesday",c); sub(/^friday$/,"Friday",c); sub(/^daily$/,"Daily",c)
      printf "| %s | %s | `%s` | %s | %s | `%s` |\n", c, $3, $8, $9, $4, $11 }' routines.tsv
    echo
    echo "Routine pages: \`https://claude.ai/code/routines/<trigger id>\`."
    echo
    echo "## Files here"
    echo
    echo "- \`<cadence>/deltas.txt\`: the only hand-written part. What makes this subject different."
    echo "- \`<cadence>/prompt.md\`: generated by \`../build.sh\`. Do not edit."
    echo "- \`<cadence>/build/\`: generated by \`../assemble.sh\`. The full prompt and the cloud body."
    echo "- \`<cadence>/runs/\`: one record per run someone inspected."
    echo "- \`<cadence>/outputs/\`: copies of published briefs pulled into the lab, one per date."
    echo
    echo "To change any of this, read \`../README.md\` first."
  } > "$d/ROUTINES.md"
  for c in daily wednesday friday; do mkdir -p "$d/$c/runs" "$d/$c/outputs"; done
  echo "wrote $d/ROUTINES.md"
done
